version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017

  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=mydatabase
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports: ["54321:11434"]
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    tty: true
    command: "serve && run llama2"
    restart: unless-stopped
    
volumes:
  mongodb_data:
  ollama: